// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFD1dM5LJcSV6-Ny0msljbMVJLARaAeJ0',
    appId: '1:382403170630:web:f3ced4d94b6221f9f39547',
    messagingSenderId: '382403170630',
    projectId: 'carbon-campus',
    authDomain: 'carbon-campus.firebaseapp.com',
    storageBucket: 'carbon-campus.appspot.com',
    measurementId: 'G-1QE24Q330B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjxX8Gqd18_wgX-I6d7zRtitSO5IvrcmE',
    appId: '1:382403170630:android:d1e4dea7c9dbb96ef39547',
    messagingSenderId: '382403170630',
    projectId: 'carbon-campus',
    storageBucket: 'carbon-campus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC11_D-DZ71o_BC6ov78DDETpFQLrCWTO8',
    appId: '1:382403170630:ios:11445fadb0ccc13df39547',
    messagingSenderId: '382403170630',
    projectId: 'carbon-campus',
    storageBucket: 'carbon-campus.appspot.com',
    iosBundleId: 'com.example.campusCarbon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC11_D-DZ71o_BC6ov78DDETpFQLrCWTO8',
    appId: '1:382403170630:ios:0782d02c14eac1dcf39547',
    messagingSenderId: '382403170630',
    projectId: 'carbon-campus',
    storageBucket: 'carbon-campus.appspot.com',
    iosBundleId: 'com.example.campusCarbon.RunnerTests',
  );
}
